# fly.toml app configuration file generated for crimson-morning-8035 on 2023-09-10T18:30:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zeal"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
